version: "3.7"

services:

  commonui-sample:
    image: vertigoala/commonui-sample
    ports:
      - 8000:80
  pgdbimage: 
    image: postgres:9.3
    env_file: ./env/.envimage
    volumes:
      - db_data_imageservice:/var/lib/postgresql/data
  elasticsearch:
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"

  image-sample:
    image: vertigoala/image-service
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.hostname == worker1
    ports:
      - 8080:8080
    depends_on:
      - pgdbimage
      - commonui-sample
    env_file: ./env/.envimage
    configs:
      - source: images-config
        target: /data/image-service/config/image-service-config.properties
    volumes:
      - data_images:/data/image-service-store
      - data_elastic:/data/image-service/elasticsearch

  image-store:
    image: nginx:alpine
    ports:
      - "8001:80"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node.hostname == worker1
    volumes:
      - type: volume
        source: data_images
        target: /usr/share/nginx/html
        volume:
          nocopy: true
configs:
  images-config:
    file: ./swarm/images-config.properties
volumes:
  db_data_imageservice:
  data_images:
  data_elastic:
