version: '3'

services:

  commonui-sample:
    image: vertigo-ala/commonui-sample
    ports:
      - 8000:8000
      - 8080:8080
    command: sh -c 'sed "s/^[ ]*listen.*/    listen 8000;/g" -i /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
  pgdbimage: 
    image: postgres:9.3
    env_file: ./env/.envimage
    container_name: pgdbimage
    volumes:
      - db_data_imageservice:/var/lib/postgresql/data
  elasticsearch:
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"


  image-sample:
    image: vertigo-ala/ala-images
#    ports:
#      - 8080:8080
    depends_on:
      - pgdbimage
      - commonui-sample
    network_mode: "service:commonui-sample"
    env_file: ./env/.envimage
    volumes:
#      - ./config:/data/images/config/
      - ./config/images-config.properties:/data/image-service/config/image-service-config.properties
      - data_images:/data/images/store
      - data_elastic:/data/images/elasticsearch

volumes:
  db_data_imageservice:
  data_images:
  data_elastic:
