version: "3.7"

services:

  commonui-sample:
    image: vertigoala/commonui-sample
    ports:
      - 8000:8000
      - 8080:8080
    # hack to make localhost:8000 work between containers too
    command: sh -c 'sed "s/^[ ]*listen.*/    listen 8000;/g" -i /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
  pgdbimage: 
    image: postgres:9.3
    env_file: ./env/.envimage
    container_name: pgdbimage
    volumes:
      - db_data_imageservice:/var/lib/postgresql/data
  elasticsearch:
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"

  image-sample:
    image: vertigoala/ala-images
    container_name: image-sample
#    ports:
#      - 8080:8080
    depends_on:
      - pgdbimage
      - commonui-sample
    network_mode: "service:commonui-sample"
    env_file: ./env/.envimage
    volumes:
#      - ./config:/data/images/config/
      - ./config/images-config.properties:/data/image-service/config/image-service-config.properties
      - data_images:/data/image-service-store
      - data_elastic:/data/image-service/elasticsearch

  image-store:
    image: nginx:alpine
    container_name: image-store
    ports:
      - "8001:80"
    volumes:
      - type: volume
        source: data_images
        target: /usr/share/nginx/html
        volume:
          nocopy: true
#      - data_images:/usr/share/nginx/html

volumes:
  db_data_imageservice:
  data_images:
  data_elastic:
